"""Tests for `hub.wrapper_supervisor`.

**The real launcher is never used here.** `wrapper/wrapper-lite-rootless` takes 6-19 s to
reach a serving state and needs a rootfs, so every test would pay that and the suite would
stop being hermetic. The measured figures are the evidence for the real binary; the
acceptance run exercises it end to end. What is pinned here is the supervisor's own logic,
and the stub launchers below reproduce every launcher behaviour that logic has to survive:

| stub | reproduces |
|---|---|
| `fake_launcher` | the ordinary case: banner, then serves `/status` with `regions: ["jp"]` |
| `fake_launcher_2fa` | `auth.cpp`'s `credentialHandler`: echoes the credentials it was given, logs `2FA: true`, then prints `2FA code: ` **with no trailing newline** (`printf` + `fflush`, `wrapper/lite/auth.cpp:66`) before reading the code |
| `fake_launcher_crash` | a launcher that dies in namespace setup and never serves |
| `fake_launcher_slow` | R6: prints its banner *then waits* before serving, so a log-based gate returns early |
| `fake_launcher_hang` | prints its banner and never serves at all |
| `fake_launcher_external` | a healthy wrapper somebody else started, for the adoption tests |

Four of these are copies of measured launcher failures rather than invented, and each one
is here because the naive implementation gets it wrong:

- `fake_launcher_slow` is the R6 pin. The banner is a lie about readiness; the real
  launcher prints it 6-19 s before it serves.
- `fake_launcher_2fa`'s unterminated prompt is the `check2FA` pin. `wrapper/gui/main.go:686`
  exists because the real prompt has no newline, so a line-oriented pump never fires.
- `fake_launcher_2fa` echoing the credentials is what makes the redaction tests mean
  something. A stub that swallowed them would pass a broken scrubber.
- `fake_launcher_banner_then_exit` is the vacuous-PASS shape found in the
  probe: print the banner, exit 0, never serve. A log-text gate calls that a good start.
"""

from __future__ import annotations

import asyncio
import contextlib
import os
import signal
import socket
import sys
import time
from pathlib import Path

import httpx
import pytest

from hub.wrapper_supervisor import (
    CHILD_TWOFA_WINDOW,
    Readiness,
    SupervisorError,
    WrapperSupervisor,
    observe_readiness,
)

# How long a test waits for a stub to serve /status. Generous for a deliberately slow
# stub, short enough that a stuck test fails in seconds rather than minutes.
EXTERNAL_READY_TIMEOUT = 15.0

# One template with a mode substituted in, rather than six scripts: the parts the
# supervisor actually depends on -- the argv spelling, the banner, the envelope shape,
# serving until SIGTERM -- are then identical across the six, so a difference in a test's
# outcome is a difference in the mode and not in the scaffolding.
_STUB_SOURCE = '''\
#!{python}
"""Stub wrapper-lite launcher (mode={mode!r}). Generated by tests/test_supervisor.py."""
import json
import os
import signal
import socket
import subprocess
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

MODE = {mode!r}
SLOW_SECONDS = {slow_seconds!r}
# Set by the /status handler in "crash_after_ready" mode, so the stub dies *because* it was
# asked whether it was up -- the only version of this that cannot race the readiness poll. A
# timer would have to outlast an unknown startup cost to guarantee `start()` saw the 200
# first, which is a flaky test on a loaded machine.
CRASH_AFTER_FIRST_STATUS = threading.Event()
# Written by "crash_once" the first time it is asked whether it is up, and read by the
# respawned copy, so exactly one crash happens per directory. `tmp_path` is per-test, so
# this cannot leak between tests.
CRASH_ONCE_MARKER = Path(".crash_once_done")
# The one socket option the real payload's listener sets (httplib.h:2047-2049), kept so a
# second bind on the same port is not refused by a TIME_WAIT remnant.
SO_REUSEPORT = getattr(socket, "SO_REUSEPORT", 0)


class _Handler(BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def do_GET(self):  # noqa: N802 - the name BaseHTTPRequestHandler requires
        if self.path == "/status":
            body = json.dumps(
                {{"code": 0, "msg": "SUCCESS", "data": {{"regions": {regions!r}}}}}
            ).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            if MODE == "crash_after_ready":
                # The response is already on the wire, so the supervisor's probe succeeds
                # and `start()` returns; the exit happens after. Dicts are ordered here.
                CRASH_AFTER_FIRST_STATUS.set()
            if MODE == "crash_once":
                # Crashes on its first /status and never again, because the marker file it
                # leaves behind is what the respawned copy reads. Self-contained: the test
                # asserts a stable wrapper comes back without having to arrange anything.
                if not CRASH_ONCE_MARKER.exists():
                    CRASH_ONCE_MARKER.write_text("")
                    CRASH_AFTER_FIRST_STATUS.set()
        else:
            self.send_error(404)

    def log_message(self, fmt, *args):
        # A request log line, not a suppressed one: the real payload logs every request,
        # and a stub that only ever logs during startup cannot tell a live pump from a
        # dead one. `test_a_raising_log_sink_does_not_kill_the_pump` depends on it.
        sys.stdout.write("2026-09-27 00:00:00.000 [INFO ] " + (fmt % args) + "\\n")
        sys.stdout.flush()


def _arg(name, default=None):
    argv = sys.argv[1:]
    for i, arg in enumerate(argv):
        if arg == name:
            return argv[i + 1]
    return default


def _listen_port():
    port = _arg("--port")
    if port is None:
        sys.exit("stub launcher in service mode requires an explicit --port")
    return int(port)


def _isolate():
    """Put this process in its own session, so a group signal cannot reach the test runner.

    Universal, not just for the R7 stub, and that is the point. A `killpg` in `stop()` aimed
    at a stub that shares the runner's process group hits the runner: the whole suite dies
    with exit 143 and reports nothing. That is a catch by catastrophe, not a test, and it
    stops the mutant from being *diagnosed* -- the run just vanishes.

    The real launcher isolates far more aggressively (`unshare(CLONE_NEWUSER|CLONE_NEWNS|
    CLONE_NEWPID)`), so this is also the more faithful stub. With every stub in its own
    session, a group-signal mutant can only ever show up as a failed assertion.
    """
    try:
        os.setsid()
    except PermissionError:  # already a group leader; the group is ours alone anyway
        pass


def _spawn_grandchild():
    """Start a process in this session that a pid signal to us will not reach.

    This is the R7 trap made observable. The launcher `unshare`s `CLONE_NEWPID`, so the
    payload `lite` is PID 1 of a nested PID namespace: a signal aimed at "the process group"
    from the supervisor does not mean what it appears to, and against the real binary it
    would not reach the payload at all.

    With the stub in its own session (see `_isolate`) the grandchild is in a group that
    contains the stub and nothing else. A signal to the child pid takes the stub and leaves
    the grandchild; a signal to the child's process group takes both. The first is correct
    and the second is the bug, so the grandchild's survival is the assertion.

    Its output goes to DEVNULL so it does not hold this process's stdout pipe open after the
    supervisor is killed -- otherwise the log pump would never see EOF.
    """
    grandchild = subprocess.Popen(
        [
            sys.executable,
            "-c",
            "import time; time.sleep(600)  # stub_grandchild: reaped by the test",
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    print("stub_grandchild pid: " + str(grandchild.pid), flush=True)


def _install_sigterm():
    # The real payload consumes SIGTERM via sigwait and shuts down gracefully
    # (lite_main.cpp:447; the spike recorded returncode=0), so exiting 0 here is what
    # makes `test_stop_terminates_the_child` a test of the supervisor's signalling rather
    # than a test of this stub. Main thread only -- `signal.signal` raises elsewhere, and
    # "crash_after_ready" serves on a worker.
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(0))


def _serve_forever(port):
    class _Server(ThreadingHTTPServer):
        allow_reuse_address = True

        def server_bind(self):
            if SO_REUSEPORT:
                self.socket.setsockopt(socket.SOL_SOCKET, SO_REUSEPORT, 1)
            super().server_bind()

    server = _Server(("127.0.0.1", port), _Handler)
    try:
        server.serve_forever(poll_interval=0.05)
    except KeyboardInterrupt:
        pass


def _chroot():
    """Model the launcher's chroot, so a base dir of "data" means `./rootfs/data`.

    `wrapper-lite-rootless.c` chdirs into `./rootfs` and chroots into it, then resolves
    `--base-dir` inside that tree, so the payload's `<base-dir>/2fa.txt` is a *host* path
    under the binary's own `rootfs/`. Modelled here because that is the mapping the
    supervisor has to reproduce on the host side to create the file at all.
    """
    base = Path("rootfs") / _arg("--base-dir", "data")
    base.mkdir(parents=True, exist_ok=True)
    return base


def _login():
    """The payload's `--login` mode, as `lite_main.cpp:538-600` behaves.

    Credentials off argv, never stdin. Then, because a spawned child has a pipe (not a tty)
    on fd 0, `auth.cpp:64`'s isatty branch cannot fire and the code comes from a file: log
    the hint, poll for it, read it, remove it. That is the real path. A stub that read the
    code from a pipe would test a channel the binary does not have, which is the mistake
    this mode exists to prevent.
    """
    creds = _arg("--login")
    if creds is None or ":" not in creds:
        print("invalid login format, expected user:pass", flush=True)
        return 1
    user = creds.split(":", 1)[0]
    # Echoed, because a child that echoes what it was handed is the case that leaks a
    # password into a log pane.
    print("2026-09-27 00:00:00.000 [INFO ] wrapper-lite login mode", flush=True)
    print("login received: " + creds, flush=True)
    needs_2fa = MODE != "login_no_2fa"
    print(
        "2026-09-27 00:00:01.000 [INFO ] credentialHandler: "
        + "{{title: , message: , 2FA: "
        + ("true" if needs_2fa else "false")
        + "}}",
        flush=True,
    )
    if not needs_2fa:
        # The account needs no code: cache the tokens and exit, which is the common real
        # outcome and the one that must not make the caller wait out a prompt timeout.
        print("2026-09-27 00:00:01.000 [INFO ] login complete, exiting", flush=True)
        return 0
    code_path = _chroot() / "2fa.txt"
    print(
        "2026-09-27 00:00:01.000 [WARN ] Enter your 2FA code into "
        + _arg("--base-dir", "data")
        + "/2fa.txt",
        flush=True,
    )

    # Polled, then removed, exactly like auth.cpp:84-99. A test that only wrote the file and
    # never checked the child consumed it would pass against a supervisor that wrote the
    # wrong path, so the consumption is the assertion that matters here.
    for _ in range({twofa_poll_tries}):
        if code_path.exists():
            code = code_path.read_text().strip()
            # The mode is reported so the owner-only assertion can be made from the only
            # side that can see it: this is a separate process, and by the time the parent
            # looks the file is already gone.
            mode = oct(code_path.stat().st_mode & 0o777)
            code_path.unlink()
            print("Code file detected! Logging in...", flush=True)
            print(
                "2FA code " + code + " accepted for " + user + " (mode " + mode + ")",
                flush=True,
            )
            print("2026-09-27 00:00:02.000 [INFO ] login complete, exiting", flush=True)
            return 0
        time.sleep({twofa_poll_seconds})
    print("2FA code timeout, aborting login", flush=True)
    return 1


def _main():
    _install_sigterm()
    _isolate()

    if MODE in ("login_2fa", "login_no_2fa"):
        # A login child is a separate, short-lived process that never listens -- see
        # `login()`'s docstring. So this mode does the handshake and exits, which is also
        # what makes `submit_2fa`'s "the login child is gone" branch reachable.
        sys.exit(_login())

    port = _listen_port()

    if MODE == "crash":
        # What a launcher that died in namespace setup looks like: one perror() line and
        # exit 1 (wrapper-lite-rootless.c:121 and neighbours). No banner, and no
        # "initializing" -- that line comes from the payload, which never got to run.
        print("mkdir ./rootfs/proc failed: Operation not permitted", flush=True)
        sys.exit(1)

    print("2026-09-27 00:00:00.000 [INFO ] initializing...", flush=True)
    print("2026-09-27 00:00:00.000 [INFO ] initializing ctx...", flush=True)

    # Every mode reaches the banner. In "slow" and "hang" it is a lie, which is the
    # point: the real launcher prints this line 6-19 s before svr.listen() succeeds.
    print(
        "2026-09-27 00:00:00.000 [INFO ] wrapper-lite listening on 127.0.0.1:"
        + str(port),
        flush=True,
    )

    if MODE == "banner_then_exit":
        sys.exit(0)
    if MODE == "hang":
        while True:
            time.sleep(0.2)
    if MODE == "slow":
        time.sleep(SLOW_SECONDS)

    print("2026-09-27 00:00:00.000 [INFO ] service ready", flush=True)

    if MODE == "setsid":
        _spawn_grandchild()
        _serve_forever(port)
        return

    if MODE in ("crash_after_ready", "crash_once"):
        # Becomes ready, then dies the moment anybody checks. This is the watcher's path:
        # a child that answers /status and then goes away is what a restart has to handle.
        # Serving happens on a worker so the main thread is free to die on demand; `sys.exit`
        # there ends the process, which is the point.
        threading.Thread(
            target=_serve_forever, args=(port,), daemon=True
        ).start()
        CRASH_AFTER_FIRST_STATUS.wait()
        print("2026-09-27 00:00:01.000 [ERROR ] simulated crash after ready", flush=True)
        sys.exit(7)

    _serve_forever(port)


if __name__ == "__main__":
    _main()
'''


def _stub(
    directory: Path,
    mode: str,
    *,
    slow_seconds: float = 1.5,
    twofa_poll_tries: int = 200,
    twofa_poll_seconds: float = 0.05,
    regions: list | None = None,
) -> Path:
    """Materialise one stub launcher and return its path.

    The shebang is `sys.executable` rather than a bare `python3` on purpose: this host's
    system python3 is 3.14.7 and the venv is 3.13.7, and a stub running under a different
    interpreter than the tests would make any failure ambiguous.

    The 2FA poll is `tries x seconds` rather than the payload's `20 x 3s`: the shape is what
    the test needs to pin -- that the supervisor writes a file the child finds and removes,
    inside a window the TTL has to fit inside -- and 60 real seconds would make the suite
    unusable. The TTL-vs-window relationship is asserted separately against the constant.
    """
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / f"stub_{mode}"
    path.write_text(
        _STUB_SOURCE.format(
            python=sys.executable,
            mode=mode,
            slow_seconds=slow_seconds,
            twofa_poll_tries=twofa_poll_tries,
            twofa_poll_seconds=twofa_poll_seconds,
            regions=["jp"] if regions is None else regions,
        ),
        encoding="utf-8",
    )
    path.chmod(0o755)
    return path


@pytest.fixture
def fake_launcher(tmp_path: Path) -> Path:
    return _stub(tmp_path, "serve")


@pytest.fixture
def fake_launcher_2fa(tmp_path: Path) -> Path:
    return _stub(tmp_path, "login_2fa")


@pytest.fixture
def fake_launcher_2fa_slow_poll(tmp_path: Path) -> Path:
    """A login child that takes ~20 s to notice a code, so the file outlives a `stop()`.

    The real child polls 20 x 3 s, so this is the same shape at a usable speed: long enough
    that `submit_2fa` can be followed immediately by `stop()`, which is the window in which
    the code file is written and then orphaned.
    """
    return _stub(tmp_path, "login_2fa", twofa_poll_tries=4, twofa_poll_seconds=5.0)


@pytest.fixture
def fake_launcher_no_2fa(tmp_path: Path) -> Path:
    """A login that succeeds and needs no code: `2FA: false`, tokens cached, exit 0."""
    return _stub(tmp_path, "login_no_2fa")


@pytest.fixture
def fake_launcher_crash(tmp_path: Path) -> Path:
    return _stub(tmp_path, "crash")


@pytest.fixture
def fake_launcher_slow(tmp_path: Path) -> Path:
    return _stub(tmp_path, "slow")


@pytest.fixture
def fake_launcher_hang(tmp_path: Path) -> Path:
    return _stub(tmp_path, "hang")


@pytest.fixture
def fake_launcher_external(tmp_path: Path) -> Path:
    return _stub(tmp_path, "external")


@pytest.fixture
def fake_launcher_setsid(tmp_path: Path) -> Path:
    """A stub in its own session, with a grandchild in it. The R7 trap, made observable."""
    return _stub(tmp_path, "setsid")


@pytest.fixture
def fake_launcher_banner_then_exit(tmp_path: Path) -> Path:
    return _stub(tmp_path, "banner_then_exit")


@pytest.fixture
def fake_launcher_crash_after_ready(tmp_path: Path) -> Path:
    """Becomes ready, then dies on every /status. The crash-loop case.

    Used for the budget tests: a watcher that "restarts until the wrapper stays up" never
    terminates against this, because every attempt looks like a success for as long as the
    process is alive.
    """
    return _stub(tmp_path, "crash_after_ready")


@pytest.fixture
def fake_launcher_crash_once(tmp_path: Path) -> Path:
    """Becomes ready, then dies exactly once, then serves normally. The recoverable case."""
    return _stub(tmp_path, "crash_once")


@pytest.fixture
def fake_launcher_no_regions(tmp_path: Path) -> Path:
    """A healthy wrapper with no account on it: HTTP 200, `code: 0`, `regions: []`.

    This is the state the real binary is in on a fresh install (`missing music/dev token`,
    the spike's own transcript), and it is *not* the same failure as never coming up. The
    stub has to serve a real 200 for the distinction to be observable at all -- a stub that
    refused connections would make both cases look alike.
    """
    return _stub(tmp_path, "no_regions", regions=[])


def _free_port() -> int:
    """An ephemeral port nothing is listening on.

    The supervisor does the same for `port=0` (see `_pick_ephemeral_port`), and that is
    inherently racy between closing the socket and the child binding. The window is not
    observable here because the stub -- like the real payload -- sets `SO_REUSEPORT`.
    """
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


_EXTERNAL: list[asyncio.subprocess.Process] = []


async def _start_external_wrapper(binary: Path) -> int:
    """Start a healthy wrapper on a port of its own, and return that port.

    Deliberately *not* a `WrapperSupervisor`: the point is a wrapper the supervisor did
    not start, which is the only shape the adoption path can encounter.
    """
    port = _free_port()
    proc = await asyncio.create_subprocess_exec(
        str(binary),
        "--base-dir",
        "data",
        "--host",
        "127.0.0.1",
        "--port",
        str(port),
        stdin=asyncio.subprocess.DEVNULL,
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.STDOUT,
    )
    _EXTERNAL.append(proc)

    deadline = time.monotonic() + EXTERNAL_READY_TIMEOUT
    async with httpx.AsyncClient(timeout=1.0) as client:
        while time.monotonic() < deadline:
            if proc.returncode is not None:
                raise RuntimeError(
                    f"the external stub exited with {proc.returncode} before serving"
                )
            try:
                response = await client.get(f"http://127.0.0.1:{port}/status")
            except httpx.HTTPError:
                response = None
            if response is not None and response.status_code == 200:
                return port
            await asyncio.sleep(0.05)
    raise RuntimeError("the external stub never served /status")


async def _stop_external_wrapper() -> None:
    while _EXTERNAL:
        proc = _EXTERNAL.pop()
        if proc.returncode is None:
            proc.terminate()
        await proc.wait()


def _stub_pids() -> dict[int, str]:
    """Every live process whose command line mentions a stub launcher.

    Linux-only by construction, and the fallback on any read error is to ignore the pid
    rather than fail the suite: this is a safety net, not the assertion.
    """
    found: dict[int, str] = {}
    for entry in os.listdir("/proc"):
        if not entry.isdigit():
            continue
        try:
            with open(f"/proc/{entry}/cmdline", "rb") as handle:
                cmdline = handle.read().decode("utf-8", "replace")
        except OSError:
            continue
        if "stub_" in cmdline:
            found[int(entry)] = cmdline
    return found


@pytest.fixture(autouse=True)
async def _no_leaked_children(tmp_path: Path):
    """Reap what a test left behind -- processes *and* files -- and say so.

    A stray stub holds its port for the rest of the session, which would turn one broken
    assertion into a cascade of unrelated ones. A stray `2fa.txt` is worse in kind: the
    payload consumes it unconditionally, so it becomes the next login's password
    (`auth.cpp:92-96`). Both are checked here rather than trusted to each test's `finally`,
    because both were observed leaking.
    """
    before = set(_stub_pids())
    yield
    await _stop_external_wrapper()
    leaked = {pid: cmdline for pid, cmdline in _stub_pids().items() if pid not in before}
    for pid in leaked:
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
    assert not leaked, f"the test leaked stub launcher processes: {sorted(leaked)}"

    stale = sorted(
        str(path)
        for pattern in ("2fa.txt", ".2fa.txt.*")
        for path in tmp_path.rglob(pattern)
        if path.is_file()
    )
    for name in stale:
        with contextlib.suppress(OSError):
            Path(name).unlink()
    assert not stale, f"the test left 2FA files behind: {stale}"


def _supervisor(binary: Path, tmp_path: Path, **kwargs) -> WrapperSupervisor:
    """A supervisor on an ephemeral port, because these tests must not collide with the
    wrapper already on 127.0.0.1:12340 on this host.

    `base_dir` is `Path("data")`, not `tmp_path`, and that is not laziness. The launcher
    resolves `--base-dir` *after* `chroot(".")` into its own `rootfs/`, so the payload's
    `2fa.txt` is a host path of `<binary dir>/rootfs/data/2fa.txt`. Passing an absolute
    `tmp_path` would put the supervisor and the stub in different trees and the 2FA tests
    would pass for the wrong reason -- the stub would find a file nobody wrote to.
    """
    return WrapperSupervisor(
        binary=binary,
        base_dir=kwargs.pop("base_dir", Path("data")),
        host="127.0.0.1",
        port=kwargs.pop("port", 0),
        log_sink=kwargs.pop("log_sink", lambda _: None),
        **kwargs,
    )


# --- readiness: HTTP, never the banner -------------------------------------


async def test_start_waits_until_regions_are_reported(fake_launcher, tmp_path):
    sup = _supervisor(fake_launcher, tmp_path)
    await sup.start()
    try:
        assert sup.running
        assert sup.bound_port > 0
        assert (await sup.status())["regions"] == ["jp"]
    finally:
        await sup.stop()


async def test_readiness_waits_for_status_not_for_the_banner(fake_launcher_slow, tmp_path):
    # the launcher prints its banner long before it actually serves
    sup = _supervisor(fake_launcher_slow, tmp_path, startup_timeout=30.0)
    started = time.monotonic()
    await sup.start()
    try:
        assert time.monotonic() - started >= 1.0, "start() returned before the port served"
        assert (await sup.status())["regions"] == ["jp"]
    finally:
        await sup.stop()


async def test_start_times_out_when_never_ready(fake_launcher_hang, tmp_path):
    sup = _supervisor(fake_launcher_hang, tmp_path, startup_timeout=1.0)
    with pytest.raises(SupervisorError, match="ready"):
        await sup.start()


async def test_a_banner_and_a_clean_exit_is_not_readiness(
    fake_launcher_banner_then_exit, tmp_path
):
    """The vacuous-PASS shape a launcher probe found, applied to `start()`.

    A launcher that prints the banner and exits 0 without ever serving is what a log-text
    gate reports as a successful start. `start()` must fail, and must do it on the exit
    rather than by waiting out the whole startup timeout.
    """
    sup = _supervisor(
        fake_launcher_banner_then_exit, tmp_path, startup_timeout=30.0, max_restarts=0
    )
    started = time.monotonic()
    with pytest.raises(SupervisorError, match="ready"):
        await sup.start()
    assert time.monotonic() - started < 20.0, "start() waited out the timeout for a dead child"
    assert not sup.running


async def test_start_reports_the_child_output_when_it_dies(fake_launcher_crash, tmp_path):
    """A namespace-setup `perror` is the only clue there is, so it must reach the message.

    `wrapper-lite-rootless.c:121` and its neighbours are one line of `perror` and exit 1;
    a message that only says "did not become ready" sends the operator to the wrong host.
    """
    sup = _supervisor(fake_launcher_crash, tmp_path, max_restarts=1)
    with pytest.raises(SupervisorError) as excinfo:
        await sup.start()
    assert "mkdir ./rootfs/proc failed" in str(excinfo.value)
    assert not sup.running


async def test_crash_is_reported_not_silently_retried_forever(fake_launcher_crash, tmp_path):
    sup = _supervisor(fake_launcher_crash, tmp_path, max_restarts=3)
    with pytest.raises(SupervisorError):
        await sup.start()


async def test_a_wrapper_with_no_account_is_not_reported_as_a_readiness_timeout(
    fake_launcher_no_regions, tmp_path
):
    """`regions: []` and "never came up" are different problems and say different things.

    Both fail `start()`, and both are reached in the field -- the second on a slow or broken
    machine, the first on every fresh install, because the payload serves `regions: []` with
    no account. Telling a user with no account that the wrapper "did not become ready" sends
    them to wait for something that is already up and will never change on its own; the
    message has to name the account and the remedy.
    """
    sup = _supervisor(fake_launcher_no_regions, tmp_path, startup_timeout=1.0)
    with pytest.raises(SupervisorError) as excinfo:
        await sup.start()
    message = str(excinfo.value)
    assert "no account is logged in" in message
    assert "did not become ready" not in message
    assert "Log in" in message
    assert not sup.running


async def test_a_wrapper_that_never_comes_up_says_so(
    fake_launcher_hang, tmp_path
):
    """The other half of the split, and it must not acquire the account wording."""
    sup = _supervisor(fake_launcher_hang, tmp_path, startup_timeout=1.0)
    with pytest.raises(SupervisorError) as excinfo:
        await sup.start()
    message = str(excinfo.value)
    assert "did not become ready" in message
    assert "no account is logged in" not in message


# --- runtime auto-restart --------------------------------------------------


async def test_a_process_exit_wakes_an_inflight_availability_waiter(
    fake_launcher_crash_after_ready, tmp_path
):
    """The app's running-job guard can observe an owned wrapper's actual process exit."""
    sup = _supervisor(
        fake_launcher_crash_after_ready, tmp_path, log_sink=lambda _line: None, max_restarts=0
    )
    try:
        await sup.start()
        readiness = await asyncio.wait_for(sup.wait_until_unavailable(), timeout=2.0)
        assert readiness.kind == "down"
        assert not sup.running
    finally:
        await sup.stop()


async def test_a_crashed_wrapper_is_restarted(fake_launcher_crash_once, tmp_path):
    """A wrapper that dies *after* serving comes back on its own.

    An unexpected exit is a restart with exponential backoff. This is the case
    round one did not implement -- the watcher reaped and reported but never respawned.

    **The observable is the supervisor's own "serving again" line, not a new pid.** Those are
    not the same moment, and the difference is a race: `_restart_after_crash` calls
    `_ensure_child()`, which spawns and sets `pid`, and only *then* awaits `_wait_ready()`
    (`wrapper_supervisor.py:1029-1030`). A poll that breaks on "the pid changed" therefore
    returns while the new child is still in `bind()`, and the HTTP GET below lands on a port
    that is not listening yet. Measured: 0 failures in isolation, 20 of 20 under 2x CPU
    oversubscription, failing with `ConnectError('All connection attempts failed')`.

    So the test waits for the line the supervisor emits *after* readiness (`:1034`), which is
    the supervisor's own definition of a successful restart -- "serving again", not "spawned
    again". `test_the_restart_budget_stops_the_loop` polls a log line for the same reason.
    """
    lines: list[str] = []
    sup = _supervisor(
        fake_launcher_crash_once, tmp_path, log_sink=lines.append, max_restarts=3
    )
    try:
        await sup.start()
        first = sup.pid
        assert first is not None
        for _ in range(200):
            if any("is serving again on" in line for line in lines):
                break
            await asyncio.sleep(0.05)
        assert any("is serving again on" in line for line in lines), (
            "the wrapper never reported serving again\n" + "\n".join(lines)
        )
        assert sup.running, "\n".join(lines)
        assert sup.pid != first, "the wrapper was never respawned"
        assert any("restarting the wrapper in" in line for line in lines), lines
        # And the respawned one is genuinely serving, not merely alive.
        assert (await sup.status())["regions"] == ["jp"]
    finally:
        await sup.stop()


async def test_the_restart_budget_stops_the_loop(fake_launcher_crash_after_ready, tmp_path):
    """A child that comes up and dies immediately must not be restarted forever.

    Each attempt looks like success to a naive watcher -- the process exists, then it is
    gone -- so "restart until it stays up" never terminates. The budget is the only thing
    that stops it, so the assertion is on the *count* of restarts and on the terminal
    message, not on a single successful restart.
    """
    lines: list[str] = []
    sup = _supervisor(
        fake_launcher_crash_after_ready, tmp_path, log_sink=lines.append, max_restarts=2
    )
    try:
        await sup.start()
        for _ in range(200):
            if any("will not be restarted" in line for line in lines):
                break
            await asyncio.sleep(0.05)
        restarts = [line for line in lines if "restarting the wrapper in" in line]
        assert len(restarts) == 2, restarts
        assert any("will not be restarted" in line for line in lines), lines
        assert not sup.running
    finally:
        await sup.stop()


async def test_the_restart_budget_is_shared_with_start(
    fake_launcher_crash_after_ready, tmp_path
):
    """One budget per epoch, so start-up retries and crash restarts cannot add up.

    Otherwise a wrapper that crashes once per start, on a supervisor with `max_restarts=3`,
    gets six spawns -- and the number a user is told is not the number that happens.
    """
    lines: list[str] = []
    sup = _supervisor(
        fake_launcher_crash_after_ready, tmp_path, log_sink=lines.append, max_restarts=1
    )
    try:
        await sup.start()
        for _ in range(200):
            if any("will not be restarted" in line for line in lines):
                break
            await asyncio.sleep(0.05)
        restarts = [line for line in lines if "restarting the wrapper in" in line]
        assert len(restarts) == 1, restarts
        assert not sup.running
    finally:
        await sup.stop()


async def test_the_restart_budget_is_bounded(fake_launcher_crash, tmp_path):
    """`max_restarts` is a budget, not a hint: `max_restarts + 1` attempts, then raise.

    Counted through the log sink, because the respawn is internal and has no other
    observable. A supervisor that retried forever would pass every other test in this
    file while never surfacing an error to the UI -- which is exactly what is forbidden
    ("自動の無限再起動は行わない").

    The shape is a bounded poll and *then* an assertion, the same shape the watcher-side
    budget test uses. An unbounded-budget mutant does not fail here, it hangs: the retry
    loop keeps going with a backoff already at its 8 s cap, so the assertion is never
    reached and the run dies on CI's global timeout with no message naming a cause. Polling
    turns that into a red test that says what went wrong.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_crash, tmp_path, log_sink=lines.append, max_restarts=2)
    task = asyncio.ensure_future(sup.start())
    done, _ = await asyncio.wait({task}, timeout=20.0)
    assert task in done, (
        "start() was still retrying after 20s, so the restart budget is not bounding the "
        f"loop. Spawns so far: {sum(1 for line in lines if 'spawning' in line)}\n{lines}"
    )
    with pytest.raises(SupervisorError):
        task.result()
    attempts = sum(1 for line in lines if "spawning" in line)
    assert attempts == 3, lines


# --- R7: signal the launcher, never the group ------------------------------


async def test_stop_signals_the_launcher_pid_and_not_its_process_group(
    fake_launcher_setsid, tmp_path
):
    """R7, asserted as a mechanism rather than as an effect.

    The child calls `setsid()` and spawns a grandchild inside that session, so it is
    structurally the situation the real launcher creates with `CLONE_NEWPID`. A signal to
    the child pid takes the child and leaves the grandchild; a signal to the child's process
    group takes both. The first is correct and the second is the bug, so the grandchild's
    survival is the assertion.

    Everything else here is satisfied by both. A `killpg` mutant in `stop()` passes the
    "child is gone" and "nothing is orphaned" checks, and without `setsid()` it does not fail
    at all -- it signals the pytest process's own group and the run dies instead of
    reporting. That is the reason the stub isolates itself: it turns a catastrophe into a
    red test.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_setsid, tmp_path, log_sink=lines.append)
    await sup.start()
    child = sup.pid
    assert child is not None
    grandchild = await _grandchild_pid(lines)
    try:
        await sup.stop()

        assert not sup.running
        with pytest.raises(ProcessLookupError):
            os.kill(child, 0)
        # Alive: the group signal did not happen. A corpse or a zombie still answers
        # `os.kill(pid, 0)`, so a little slack is needed for a signal that *was* sent to
        # land and be reaped.
        await asyncio.sleep(0.3)
        grandchild_alive = True
        try:
            os.kill(grandchild, 0)
        except ProcessLookupError:
            grandchild_alive = False
        assert grandchild_alive, (
            f"grandchild {grandchild} died with the child, so stop() signalled the "
            f"process group, not the launcher pid. That is the R7 bug, and against the "
            f"real launcher it would leave the payload running as PID 1 of its nested "
            f"namespace. Log: {lines}"
        )
    finally:
        # After the assertion, never before: this test's whole claim is that the grandchild
        # outlives `stop()`, so cleaning it up early would make the claim unfalsifiable.
        with contextlib.suppress(ProcessLookupError, PermissionError):
            os.kill(grandchild, 9)


async def _grandchild_pid(lines: list[str], *, tries: int = 100) -> int:
    for _ in range(tries):
        for line in lines:
            if line.startswith("stub_grandchild pid: "):
                return int(line.rsplit(" ", 1)[1])
        await asyncio.sleep(0.02)
    raise AssertionError(f"the stub never reported a grandchild pid: {lines}")


def _detections(lines: list[str]) -> list[int]:
    """Log positions where a login child consumed a code file."""
    return [n for n, line in enumerate(lines) if "Code file detected" in line]


def _prompts(lines: list[str]) -> list[int]:
    """Log positions where a login child said it was waiting for a code.

    Positional rather than by value on purpose: the scrubber redacts codes *and* account
    names, so an assertion naming either would pass whether or not the right one was used.
    """
    return [n for n, line in enumerate(lines) if "Enter your 2FA code into" in line]


async def test_stop_leaves_no_orphan_after_a_failed_start(fake_launcher_hang, tmp_path):
    """A failed `start()` must not leave its child behind.

    This is the one place a stray process is invisible: the test never saw a pid, so the
    port it was holding stays occupied for the rest of the session.
    """
    sup = _supervisor(fake_launcher_hang, tmp_path, startup_timeout=1.0)
    with pytest.raises(SupervisorError):
        await sup.start()
    assert not sup.running
    assert sup.pid is None


async def test_stop_is_idempotent(fake_launcher, tmp_path):
    sup = _supervisor(fake_launcher, tmp_path)
    await sup.start()
    await sup.stop()
    await sup.stop()
    assert not sup.running


# --- R8: adopt an existing healthy wrapper ---------------------------------


async def test_adopts_a_healthy_wrapper_already_on_the_port(fake_launcher_external, tmp_path):
    port = await _start_external_wrapper(fake_launcher_external)
    sup = _supervisor(fake_launcher_external, tmp_path, port=port, adopt_existing=True)
    await sup.start()
    try:
        assert sup.adopted is True
        assert sup.pid is None  # we did not spawn anything
        assert sup.bound_port == port
        assert (await sup.status())["regions"] == ["jp"]
    finally:
        await sup.stop()
        await _stop_external_wrapper()


async def test_does_not_adopt_when_adopt_existing_is_false(fake_launcher_external, tmp_path):
    port = await _start_external_wrapper(fake_launcher_external)
    sup = _supervisor(fake_launcher_external, tmp_path, port=port, adopt_existing=False)
    with pytest.raises(SupervisorError, match="port"):
        await sup.start()
    assert not sup.adopted
    await _stop_external_wrapper()


async def test_login_on_an_adopted_supervisor_is_refused(fake_launcher_external, tmp_path):
    port = await _start_external_wrapper(fake_launcher_external)
    sup = _supervisor(fake_launcher_external, tmp_path, port=port)
    await sup.start()
    try:
        with pytest.raises(SupervisorError, match="adopted"):
            await sup.login("u", "p")
    finally:
        await sup.stop()
        await _stop_external_wrapper()


async def test_stop_does_not_kill_an_adopted_wrapper(fake_launcher_external, tmp_path):
    """`stop()` shuts down what it started, and nothing else.

    The adopted process belongs to somebody else -- on this host, the user's own wrapper
    QEMU on 127.0.0.1:12340 -- so a `stop()` that signalled it would take down a service
    the hub does not own.
    """
    port = await _start_external_wrapper(fake_launcher_external)
    external = _EXTERNAL[0]
    sup = _supervisor(fake_launcher_external, tmp_path, port=port)
    await sup.start()
    await sup.stop()
    await asyncio.sleep(0.2)
    assert external.returncode is None
    assert sup.pid is None
    await _stop_external_wrapper()


# --- the port pre-flight ---------------------------------------------------


async def test_a_port_held_by_a_non_wrapper_fails_fast(fake_launcher, tmp_path):
    """A silent TCP listener on the port is the trap the port pre-flight exists for.

    The payload would get EADDRINUSE, `svr.listen()` would return at once and
    `lite_main.cpp:705` would make it signal *itself*, producing a log line that reads
    exactly like an external kill. The pre-flight exists so that is never the report the
    operator is given.
    """
    port = _free_port()
    held: list[asyncio.StreamWriter] = []

    def _silent(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        held.append(writer)

    # The listener answers nothing for as long as the pre-flight runs, because answering
    # nothing is the scenario. What it accepted is closed in the cleanup below, and that is
    # not tidying -- on Python 3.12 it is the difference between this test finishing and
    # this test never finishing.
    #
    # `Server.wait_closed()` does not return while the server holds a connection, and
    # `Server.close()` only wakes it when that count is already zero. CPython 3.13 tracks
    # the count as a `weakref.WeakSet` of client transports and ships `close_clients()`;
    # 3.12 tracks an integer, and the probe's connection -- accepted here, and never closed
    # by the old `lambda r, w: None`, which being not a coroutine got neither a task nor a
    # close (asyncio/streams.py) -- keeps it above zero for good. So on 3.12 the `finally`
    # below became an infinite await, which is how the suite was found wedged in CI with
    # 89% of its tests already passed and 20 minutes gone.
    blocker = await asyncio.start_server(_silent, "127.0.0.1", port)
    sup = _supervisor(fake_launcher, tmp_path, port=port)
    try:
        with pytest.raises(SupervisorError, match="port") as excinfo:
            await sup.start()
        assert "another process" in str(excinfo.value)
    finally:
        blocker.close()
        for writer in held:
            writer.close()
        await blocker.wait_closed()
    assert not sup.running


async def test_no_preflight_when_port_is_zero(fake_launcher, tmp_path):
    """`port=0` means "pick one for me", so there is nothing to pre-flight.

    A pre-flight against port 0 would probe nothing and either pass silently or -- worse
    -- adopt a wrapper "on port 0", which is not a thing.
    """
    sup = _supervisor(fake_launcher, tmp_path, port=0)
    await sup.start()
    try:
        assert sup.bound_port != 0
    finally:
        await sup.stop()


# --- login -----------------------------------------------------------------


async def test_login_raises_a_challenge_when_2fa_is_prompted(fake_launcher_2fa, tmp_path):
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    ch = await sup.login("user", "pass")
    assert ch.id
    assert ch.expires_at > time.time()
    await sup.submit_2fa(ch.id, "123456")
    await sup.stop()


async def test_submit_2fa_writes_the_file_the_child_polls_for(
    fake_launcher_2fa, tmp_path
):
    """The end-to-end shape of the real exchange, minus Apple.

    `auth.cpp:62,84-99` builds `<base-dir>/2fa.txt`, polls for it, reads it and *removes*
    it. The stub does the same, so this passes only if the supervisor (1) triggered on the
    log line, (2) created the file at the path the child is actually watching -- which is
    inside the launcher's `rootfs/`, because the base dir is resolved after `chroot(".")` --
    and (3) the child found it and took it away again.

    Checking that the file was *consumed* is the part that matters. Asserting only that the
    supervisor wrote something would pass against a path the child never looks at, which is
    the most likely way for this to be wrong.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    expected = tmp_path / "rootfs" / "data" / "2fa.txt"
    assert not expected.exists(), "the stub should not have created the file itself"

    challenge = await sup.login("user", "pass")
    await sup.submit_2fa(challenge.id, "123456")

    for _ in range(200):
        if any("Code file detected" in line for line in lines):
            break
        await asyncio.sleep(0.02)
    joined = "\n".join(lines)
    assert "Code file detected" in joined, joined
    assert not expected.exists(), "the child removes the file; leaving it is a leak"
    await sup.stop()


async def test_the_twofa_file_is_owner_only(fake_launcher_2fa, tmp_path):
    """Mode 0600, because the launcher creates its base dir 0777.

    `wrapper-lite-rootless.c:142` is `mkdir(base_dir, 0777)`, so the file's own mode is the
    only thing keeping a six-digit code off other readers in that container. Asserted from
    the log rather than from the filesystem because the child removes the file within one
    poll iteration of it being written -- and the child is the only process that can see the
    mode at all.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    challenge = await sup.login("user", "pass")
    await sup.submit_2fa(challenge.id, "123456")
    for _ in range(200):
        if any("accepted" in line for line in lines):
            break
        await asyncio.sleep(0.02)
    assert any("(mode 0o600)" in line for line in lines), lines
    await sup.stop()


async def test_login_does_not_need_the_serving_child(fake_launcher_2fa, tmp_path):
    """`login()` runs its own process, so it cannot deadlock against `start()`.

    The login mode never listens (`lite_main.cpp:538-600`): it caches tokens and exits.
    That is what makes the ordering work at all -- `start()` waits for `regions`, regions
    stay empty until an account is logged in, and the one operation that fixes that must
    not itself be waiting on `start()`.
    """
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    assert not sup.running
    challenge = await sup.login("u", "p")
    try:
        assert challenge.expires_at > time.time()
        assert not sup.running, "a login child is not a serving child"
    finally:
        await sup.stop()


async def test_a_login_that_needs_no_2fa_reports_at_once(fake_launcher_no_2fa, tmp_path):
    """An account with no 2FA is the common outcome, and it must not cost a prompt timeout.

    The login mode exits by itself when it is done, so `login()` waits for the prompt *or*
    the exit. Without that, the most frequent real outcome -- a correct password on an
    account that needs no code -- would block for the whole `LOGIN_PROMPT_TIMEOUT` before
    the caller heard anything, and the user would think the hub had hung.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_no_2fa, tmp_path, log_sink=lines.append)
    started = time.monotonic()
    with pytest.raises(SupervisorError) as excinfo:
        await sup.login("user", "pass")
    assert time.monotonic() - started < 5.0, "waited out the prompt timeout"
    message = str(excinfo.value)
    assert "without asking for a 2FA code" in message
    assert "login complete, exiting" in message, message
    await sup.stop()


async def test_a_login_child_is_not_left_running(fake_launcher_2fa, tmp_path):
    """`stop()` reaps the login child too, and the pid is really gone.

    A login child holds the credentials in its argv; leaving it alive past `stop()` would
    leave them readable in `/proc/<pid>/cmdline` indefinitely.

    The check is a *delta* over the whole machine, not an absolute: an unrelated stub from
    another session on this host would otherwise fail a test that has nothing to do with it.
    """
    before = set(_stub_pids())
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    await sup.login("u", "p")
    await sup.stop()
    leaked = {pid for pid in _stub_pids() if pid not in before}
    assert not leaked, f"a login child survived stop(): {sorted(leaked)}"


async def test_twofa_ttl_is_the_child_window(fake_launcher_2fa, tmp_path):
    """The default TTL is the payload's own 60 s, and the deadline cannot exceed it.

    `auth.cpp:83-88` polls `20 x sleep(3)` and then gives up. A TTL longer than that would
    promise a deadline the wrapper does not honour -- the user would type a code in good
    faith and the login would already be dead. 300 s, which round one defaulted to, was
    five times the real window.

    The deadline is measured from when the *child* started counting, not from when the
    challenge is minted, and `twofa_ttl` is clamped to the child's window, so no setting can
    produce a deadline the child has already passed.
    """
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    challenge = await sup.login("u", "p")
    try:
        # Measured from *after* `login()` returned, because the marker is stamped when it is
        # seen and the challenge is handed over immediately afterwards. So the time left is
        # at most the child's whole window and very nearly all of it.
        remaining = challenge.expires_at - time.time()
        assert CHILD_TWOFA_WINDOW - 1.0 <= remaining <= CHILD_TWOFA_WINDOW
    finally:
        await sup.stop()


async def test_a_ttl_longer_than_the_child_window_is_clamped(
    fake_launcher_2fa, tmp_path
):
    """`twofa_ttl` is a preference; the child's 60 s is the ceiling.

    A configuration that asks for 300 s gets 60, because the alternative is a UI promising
    a user four minutes to type a code the wrapper stopped listening for after one.
    """
    sup = _supervisor(fake_launcher_2fa, tmp_path, twofa_ttl=300.0)
    challenge = await sup.login("u", "p")
    try:
        assert challenge.expires_at - time.time() <= CHILD_TWOFA_WINDOW
    finally:
        await sup.stop()


# --- I1: a leftover 2fa.txt is a credential, not litter --------------------


async def test_a_leftover_twofa_file_is_removed_before_a_new_login(
    fake_launcher_2fa, tmp_path
):
    """A stale file is consumed, not ignored -- which is why it has to be removed.

    `auth.cpp:84` guards only the *wait* on `file_exists`. The `fopen` + `fscanf` at
    `:92-96`, which appends the file's contents to the password, is unconditional, so a
    leftover file short-circuits the whole poll and is appended to the new login's password
    without ever prompting anyone.

    The file is planted here exactly as a killed login would leave it, and the assertion is
    that the next login waits for a real code instead of consuming it.
    """
    lines: list[str] = []
    stale = tmp_path / "rootfs" / "data" / "2fa.txt"
    stale.parent.mkdir(parents=True)
    stale.write_text("999999")
    stale.chmod(0o600)

    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    try:
        challenge = await sup.login("user", "pass")
        await asyncio.sleep(0.3)
        assert not _detections(lines), lines
        assert any("removed a leftover 2FA file" in line for line in lines), lines

        # And the login is still waiting, so a real code still works. The assertion is on
        # *ordering*, not on the code or the account name: both are redacted by the scrubber
        # (the username is a credential too), so an assertion naming either would
        # be vacuous. What matters is that the file was consumed exactly once and only
        # after this login was prompted.
        await sup.submit_2fa(challenge.id, "123456")
        for _ in range(200):
            if _detections(lines):
                break
            await asyncio.sleep(0.02)
        assert len(_detections(lines)) == 1, lines
        assert _detections(lines)[0] > _prompts(lines)[-1], lines
        assert any("accepted for" in line for line in lines), lines
    finally:
        await sup.stop()


async def test_a_stopped_login_leaves_no_twofa_file(
    fake_launcher_2fa_slow_poll, tmp_path
):
    """`stop()` removes the code file it orphaned.

    The child only unlinks at `auth.cpp:99`, the last thing the login does, so a SIGTERM
    reliably prevents it. Whatever the supervisor wrote has to be cleaned up by the
    supervisor, or it becomes the next login's password.
    """
    path = tmp_path / "rootfs" / "data" / "2fa.txt"
    sup = _supervisor(fake_launcher_2fa_slow_poll, tmp_path)
    challenge = await sup.login("user", "pass")
    await sup.submit_2fa(challenge.id, "111111")
    assert path.exists(), "the write did not happen, so this test proves nothing"
    await sup.stop()
    assert not path.exists()


async def test_a_second_login_does_not_inherit_the_first_logins_code(
    fake_launcher_2fa_slow_poll, tmp_path
):
    """The review's reproduction, as a test.

    Log in, hand over a code, stop before the child polls it, then log in again with a
    different account. Without the cleanup the second login finds the first login's file,
    consumes it, and reports `2FA code 111111 accepted for user2` -- a code nobody typed for
    that account, appended to its password by `auth.cpp:92-96`.
    """
    lines: list[str] = []
    path = tmp_path / "rootfs" / "data" / "2fa.txt"
    sup = _supervisor(fake_launcher_2fa_slow_poll, tmp_path, log_sink=lines.append)
    first = await sup.login("user1", "pass1")
    await sup.submit_2fa(first.id, "111111")
    await sup.stop()
    assert not path.exists(), "the first login's code survived stop()"

    try:
        second = await sup.login("user2", "pass2")
        await asyncio.sleep(0.3)
        # The claim: nothing was consumed until *this* login was given a code. Codes and
        # account names are both redacted, so the assertion is positional -- the single
        # detection has to come after the second login's own prompt.
        assert not _detections(lines), lines
        assert len(_prompts(lines)) == 2, lines

        await sup.submit_2fa(second.id, "222222")
        for _ in range(400):
            if _detections(lines):
                break
            await asyncio.sleep(0.05)
        assert len(_detections(lines)) == 1, lines
        assert _detections(lines)[0] > _prompts(lines)[-1], lines
        assert sum("accepted for" in line for line in lines) == 1, lines
    finally:
        await sup.stop()
    assert not path.exists()


async def test_expired_challenge_is_rejected(fake_launcher_2fa, tmp_path):
    sup = _supervisor(fake_launcher_2fa, tmp_path, twofa_ttl=0.01)
    ch = await sup.login("u", "p")
    await asyncio.sleep(0.05)
    with pytest.raises(SupervisorError, match="expired"):
        await sup.submit_2fa(ch.id, "000000")
    await sup.stop()


async def test_a_challenge_is_single_use(fake_launcher_2fa, tmp_path):
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    ch = await sup.login("u", "p")
    await sup.submit_2fa(ch.id, "123456")
    with pytest.raises(SupervisorError, match="challenge"):
        await sup.submit_2fa(ch.id, "123456")
    await sup.stop()


async def test_an_unknown_challenge_is_rejected(fake_launcher_2fa, tmp_path):
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    await sup.login("u", "p")
    with pytest.raises(SupervisorError, match="challenge"):
        await sup.submit_2fa("not-a-real-id", "123456")
    await sup.stop()


async def test_submit_2fa_after_the_login_child_gone_is_reported(
    fake_launcher_2fa, tmp_path
):
    """A dead login child is a fact to report, not a `FileNotFoundError` to leak.

    Same shape as the EADDRINUSE trap: a login that fails because the process went away has
    to
    say so in the wrapper's own terms. A code written into the void is the alternative --
    the next `login()` would find the stale file and log in with the wrong code.
    """
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    ch = await sup.login("u", "p")
    await sup.stop()
    with pytest.raises(SupervisorError, match="login process is not running"):
        await sup.submit_2fa(ch.id, "123456")


async def test_credentials_never_reach_the_log_sink(fake_launcher_2fa, tmp_path):
    lines: list[str] = []
    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    await sup.login("SECRET_USER", "SECRET_PASS")
    await asyncio.sleep(0.1)
    assert not any("SECRET_USER" in line or "SECRET_PASS" in line for line in lines), lines
    await sup.stop()


async def test_the_2fa_code_never_reaches_the_log_sink(fake_launcher_2fa, tmp_path):
    lines: list[str] = []
    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    challenge = await sup.login("user", "pass")
    await sup.submit_2fa(challenge.id, "654321")
    await asyncio.sleep(0.2)
    assert not any("654321" in line for line in lines), lines
    assert any("accepted" in line for line in lines), "the stub never confirmed the code"
    await sup.stop()


async def test_a_shorter_secret_does_not_leave_a_fragment_behind(fake_launcher_2fa, tmp_path):
    """Redaction is longest-match-first, or a username that prefixes a password leaks it.

    `SECRET` is a prefix of `SECRET_PASS`. Replacing the short one first turns the longer
    one into `***_PASS` and the password survives in the log verbatim. The stub echoes the
    credentials it was handed on argv, so this is the real shape -- and it is now more
    important than it was, because argv is where the credentials actually go.
    """
    lines: list[str] = []
    sup = _supervisor(fake_launcher_2fa, tmp_path, log_sink=lines.append)
    await sup.login("SECRET", "SECRET_PASS")
    await asyncio.sleep(0.15)
    joined = "\n".join(lines)
    assert "SECRET" not in joined
    assert "PASS" not in joined
    assert any("login received" in line for line in lines), lines
    await sup.stop()


async def test_a_second_login_supersedes_the_first(fake_launcher_2fa, tmp_path):
    """One login child at a time, and the first challenge dies with the first one.

    Two live login children would both watch the same `2fa.txt`, and the code would go to
    whichever polled first. Worse, a code offered against the *first* challenge after a
    second `login()` would be picked up by the second login and appended to the wrong
    account's password (`auth.cpp:92-96`), so the stale challenge has to stop existing.
    """
    sup = _supervisor(fake_launcher_2fa, tmp_path)
    first = await sup.login("user1", "pass1")
    second = await sup.login("user2", "pass2")
    try:
        assert first.id != second.id
        with pytest.raises(SupervisorError, match="challenge"):
            await sup.submit_2fa(first.id, "111111")
        await sup.submit_2fa(second.id, "222222")
    finally:
        await sup.stop()


async def test_a_raising_log_sink_does_not_kill_the_pump(fake_launcher, tmp_path):
    """The pump outlives its own sink.

    The API layer's sink appends to an HTMX log pane; a client that disconnects mid-write
    raises in there. If that reached the pump task the supervisor would lose its line
    reader -- and, because the child is still producing output, the child would block on a
    full pipe and the whole wrapper would wedge.
    """
    calls = {"n": 0}

    def _explode(line: str) -> None:
        calls["n"] += 1
        raise RuntimeError("the log pane is gone")

    sup = _supervisor(fake_launcher, tmp_path, log_sink=_explode)
    try:
        await sup.start()
        assert (await sup.status())["regions"] == ["jp"]
        # Every /status request makes the stub log a line, so a pump that died with its
        # first sink call stops incrementing this while the server is perfectly healthy.
        before = calls["n"]
        for _ in range(3):
            await sup.status()
        assert calls["n"] > before, "the pump stopped delivering after the sink raised"
        assert sup.running
    finally:
        await sup.stop()


# --- the edges around start() ---------------------------------------------


async def test_start_on_a_missing_binary_fails_with_the_path(fake_launcher, tmp_path):
    missing = tmp_path / "not-there" / "wrapper-lite-rootless"
    sup = _supervisor(missing, tmp_path)
    with pytest.raises(SupervisorError) as excinfo:
        await sup.start()
    assert "not-there" in str(excinfo.value)


async def test_status_before_start_is_reported_not_an_httpx_error(fake_launcher, tmp_path):
    sup = _supervisor(fake_launcher, tmp_path)
    with pytest.raises(SupervisorError, match="not started"):
        await sup.status()


# --------------------------------------------------------------------------- #
# observe_readiness -- the observation every caller renders its vocabulary from.
# --------------------------------------------------------------------------- #
class _Observed:
    """A supervisor's observed face only: `running`, and a `status` that answers or fails.

    The double is this small on purpose. `observe_readiness` is a function over the
    public face, so a caller carrying `running`/`status()` is observed exactly like the
    real supervisor -- which is also the assertion that the seam stayed two members.
    """

    def __init__(
        self,
        *,
        running: bool,
        payload: dict | None = None,
        error: Exception | None = None,
    ) -> None:
        self.running = running
        self._payload = payload
        self._error = error
        self.asks = 0

    async def status(self) -> dict:
        self.asks += 1
        if self._error is not None:
            raise self._error
        assert self._payload is not None
        return self._payload


async def test_a_wrapper_with_no_process_is_down_and_is_never_asked() -> None:
    """`down` comes from the supervisor's own record, not from a failed request."""
    observed = _Observed(running=False)
    readiness = await observe_readiness(observed)
    assert readiness.kind == "down"
    assert observed.asks == 0, "a process nobody has must not be spoken to"


async def test_a_failed_probe_is_unreachable_and_never_down() -> None:
    """The payload may be perfectly healthy; a check that failed to ask says nothing.

    This is the round-3 symmetry rule in its one-home form: an uninformative
    observation supports no specific claim, in either direction.
    """
    observed = _Observed(running=True, error=ConnectionError("boom"))
    readiness = await observe_readiness(observed)
    assert readiness.kind == "unreachable"
    assert readiness.detail == "ConnectionError: boom", (
        "the probe's own error is the only thing known about the wrapper, so it is "
        "what the caller gets to say"
    )


async def test_serving_without_regions_is_no_account() -> None:
    """Up, answering, and unable to serve a download -- the fresh-install state."""
    observed = _Observed(running=True, payload={"regions": []})
    readiness = await observe_readiness(observed)
    assert readiness.kind == "no-account"


async def test_serving_keeps_the_regions_it_observed() -> None:
    observed = _Observed(running=True, payload={"regions": ["jp", "us"]})
    readiness = await observe_readiness(observed)
    assert isinstance(readiness, Readiness)
    assert readiness.kind == "serving"
    assert readiness.regions == ("jp", "us"), (
        "the render needs the fact, not just the verdict: wrapper_state answers with "
        "these and start() gates on them"
    )
